# Generated by Django 4.1.2 on 2022-10-18 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('master_rid', models.AutoField(primary_key=True, serialize=False)),
                ('master_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'master',
            },
        ),
        migrations.CreateModel(
            name='RegistrationModel',
            fields=[
                ('user_rid', models.AutoField(primary_key=True, serialize=False)),
                ('user_first_name', models.CharField(max_length=50)),
                ('user_last_name', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=50)),
                ('user_mobile', models.CharField(max_length=10, null=True)),
                ('user_gender', models.IntegerField(null=True)),
                ('user_dob', models.DateField()),
                ('user_calculated_dob', models.DateField()),
                ('user_address', models.TextField()),
                ('user_password', models.TextField(null=True)),
                ('user_created_datetime', models.DateTimeField()),
                ('user_mod_datetime', models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 18, 14, 19, 54, 134961, tzinfo=datetime.timezone.utc))),
                ('user_otp', models.IntegerField(null=True)),
                ('user_active', models.IntegerField(default=1)),
                ('user_ip_address', models.CharField(max_length=50)),
                ('user_type', models.IntegerField(default=2)),
                ('user_entity_rid', models.IntegerField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
