# Generated by Django 4.1.2 on 2022-10-18 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationmodel',
            name='user_mod_datetime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 18, 14, 20, 31, 189046, tzinfo=datetime.timezone.utc)),
        ),
    ]
