# Generated by Django 4.1.2 on 2022-10-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Master",
            fields=[
                ("master_rid", models.AutoField(primary_key=True, serialize=False)),
                ("master_name", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "master",
            },
        ),
    ]
