# Generated by Django 4.1.2 on 2022-10-19 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_registrationmodel_user_mod_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationmodel',
            name='user_mod_datetime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 19, 13, 27, 13, 768612, tzinfo=datetime.timezone.utc)),
        ),
    ]
