# Generated by Django 4.1.2 on 2022-10-19 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_registrationmodel_user_mod_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationmodel',
            name='user_address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='registrationmodel',
            name='user_calculated_dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='registrationmodel',
            name='user_created_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='registrationmodel',
            name='user_dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='registrationmodel',
            name='user_email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registrationmodel',
            name='user_first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registrationmodel',
            name='user_last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registrationmodel',
            name='user_mod_datetime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 19, 13, 30, 57, 447947, tzinfo=datetime.timezone.utc)),
        ),
    ]
