# Generated by Django 4.1.2 on 2022-10-19 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_alter_registrationmodel_user_mod_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationmodel',
            old_name='user_entity_rid',
            new_name='user_product_rid',
        ),
    ]
