# Generated by Django 4.1.2 on 2022-10-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_rename_user_entity_rid_registrationmodel_user_product_rid'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationmodel',
            name='user_email_verified',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registrationmodel',
            name='user_mobile_verified',
            field=models.SmallIntegerField(default=0),
        ),
    ]
