# Generated by Django 4.1.2 on 2022-10-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageModel',
            fields=[
                ('msg_rid', models.AutoField(primary_key=True, serialize=False)),
                ('msg_number', models.CharField(max_length=10)),
                ('msg_generated_datetime', models.DateTimeField()),
                ('msg_status', models.SmallIntegerField(default=0)),
                ('msg_product_rid', models.SmallIntegerField()),
                ('msg_count', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'mobile_message',
            },
        ),
    ]
